services:
  trustpoint:
    build: .
    image: trustpoint2023/trustpoint:latest
    container_name: trustpoint
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
    environment:
      DATABASE_ENGINE: "django.db.backends.postgresql"
      DATABASE_NAME: "trustpoint_db"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "testing321"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"

  postgres:
    build:
      context: .
      dockerfile: postgre.Dockerfile
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "testing321"
      POSTGRES_DB: "trustpoint_db"

volumes:
  postgres_data:
